server {
    listen 80;
    listen [::]:80;

    server_name n0kia-0024.com;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://n0kia-0024.com$request_uri;
        #proxy_pass http://api:5050;
    }
}

server {
    listen 443 ssl http2 default_server;
    listen [::]:443 ssl http2;

    server_name n0kia-0024.com;

    ssl_certificate /etc/nginx/ssl/live/n0kia-0024.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/n0kia-0024.com/privkey.pem;

    location / {
       proxy_pass http://51.158.69.60:5050;
    }
}
