include:
- local: 'api/api-ci.yml'

stages:
- backend_tests
- build

build_image:
  ##TODO: conditionner le build (on build que si on déploie en prod)
  stage: build
  tags:
  - general
  only:
  - main
  image: docker:27.1.1
  services:
  - name: docker:27.1.1-dind
    alias: docker
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/api-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - echo "Building docker image..."
  - docker build --pull -t $IMAGE_TAG -f ./api/docker/Dockerfile .
  - docker push $IMAGE_TAG
  - echo "Done."

