include:
- local: 'api/api-ci.yml'

stages:
- backend_tests
- tag_release
- deploy

create_minor_release_tag:
  stage: tag_release
  script:
  - VERSION_FILE="VERSION"
  - if [ ! -f $VERSION_FILE ]; then echo "1.0.0" > $VERSION_FILE; fi
  - VERSION=$(cat $VERSION_FILE)
  - IFS='.' read -r major minor patch <<< "$VERSION"
  - minor=$((minor + 1))
  - VERSION="$major.$minor.0"
  - echo $VERSION > $VERSION_FILE
  - git tag "v.$VERSION" || exit 1
  - git push https://oauth2:$GITLAB_TOKEN@gitlab.mt.glassworks.tech/a_goarnisson/nokia0024.git "v.$VERSION" || exit 1
  when: manual
  only:
  - main

create_major_release_tag:
  stage: tag_release
  script:
  - VERSION_FILE="VERSION"
  - if [ ! -f $VERSION_FILE ]; then echo "1.0.0" > $VERSION_FILE; fi
  - VERSION=$(cat $VERSION_FILE)
  - IFS='.' read -r major minor patch <<< "$VERSION"
  - major=$((major + 1))
  - VERSION="$major.0.0"
  - echo $VERSION > $VERSION_FILE
  - git tag "v.$VERSION" || exit 1
  - git push https://oauth2:$GITLAB_TOKEN@gitlab.mt.glassworks.tech/a_goarnisson/nokia0024.git "v.$VERSION" || exit 1
  when: manual
  only:
  - main

deploy_production:
  needs:
  - create_minor_release_tag
  - create_major_release_tag
  stage: deploy
  script:
  - if ! which ssh-agent > /dev/null; then apt-get update -y && apt-get install openssh-client -y; fi
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  - git pull origin main
  - cd api
  - docker compose up -d
  only:
  - main
