image: node:latest

variables:
  TOKEN_SECRET_KEY: test
  POSTGRES_USER: root
  POSTGRES_PASSWORD: password

services:
- postgres:latest

cache:
  paths:
  - node_modules/

stages:
- backend_tests
- build

backend_tests-job:
  stage: backend_tests
  script:
  - cd api
  - npm install
  - npm run test
  artifacts:
    when: always

build_image:
  stage: build
  tags:
  - general
  only:
  - main
  image: docker:27.1.1
  services:
  - name: docker:27.1.1-dind
    alias: docker
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE/api-$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - echo "Building docker image..."
  - docker build --pull -t $IMAGE_TAG -f ./api/docker/Dockerfile .
  - docker push $IMAGE_TAG
  - echo "Done."



