image: node:latest

variables:
  TOKEN_SECRET_KEY: test
  POSTGRES_USER: root
  POSTGRES_PASSWORD: password

services:
- postgres:latest

cache:
  paths:
  - node_modules/

stages:
- backend_tests

backend_tests-job:
  stage: backend_tests
  script:
  - cd api
  - npm install
  - npm run test
  artifacts:
    when: always




