version: '3.9'

services:
  nokia_api:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "5050:5050"
    environment:
      - TOKEN_SECRET_KEY=dev
      - PORT=5050      
    networks:
      - nokia-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    
  nokia_db:
    image: postgres:16
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./nokia_api/db/db-data:/var/lib/postgresql/data
      - ./nokia_api/db/postgres.cnf:/etc/postgresql/postgresql.conf
    command: -p 5433
    networks:
      - nokia-network
  
  proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/api-https-setup.nginx.conf:/etc/nginx/conf.d/api.nginx.conf
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - nokia-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - nokia-network

networks:
  nokia-network:
    driver: bridge    