image: node:latest

variables:
  TOKEN_SECRET_KEY: test
  POSTGRES_USER: root
  POSTGRES_PASSWORD: password

services:
- postgres:latest

cache:
  paths:
  - node_modules/

stages:
- backend_tests
- tag_release
- deploy

backend_tests-job:
  stage: backend_tests
  script:
  - npm install
  - npm run test
  artifacts:
    when: always

create_release_tag:
  stage: tag_release
  script:
  - export VERSION=$(date +'%Y.%m.%d-%H%M')
  - git tag $VERSION
  - git push https://oauth2:$GITLAB_TOKEN@gitlab.mt.glassworks.tech/a_goarnisson/nokia0024.git $VERSION
  when: manual
  only:
  - main

deploy_production:
  stage: deploy
  script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  - git pull origin main
  - cd api
  - docker compose up -d
  only:
  - main
  dependencies:
  - create_release_tag
